### ISSUE TITLE
idea无法编译

### ISSUE THREAD

**Issue by li7hai26** [SpringForAll/isona#7]
只能使用Eclipse进行编译。。。。。

**Comment by dyc87112** [comment]
什么错误？

**Comment by li7hai26** [comment]
"/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/jdk/Contents/Home/jre/bin/java" -Dmaven.multiModuleProjectDirectory=/Users/lihaifeng/IdeaProjects/isona "-Dmaven.home=/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-javaagent:/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/lib/idea_rt.jar=50914:/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 2018.1 EAP.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version=2018.1 -s /Users/lihaifeng/Desktop/Coding/apache-maven-3.5.2/conf/settings.xml clean -f pom.xml
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-storage:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-storage/pom.xml) points at com.spring4all:isona instead of com.spring4all:isona-parent, please verify your project structure @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-storage:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-core:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-core/pom.xml) points at com.spring4all:isona instead of com.spring4all:isona-parent, please verify your project structure @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-core:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-web:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-web/pom.xml) points at com.spring4all:isona instead of com.spring4all:isona-parent, please verify your project structure @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-web:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10
[ERROR] Child module /Users/lihaifeng/IdeaProjects/isona/isona-example-consul of /Users/lihaifeng/IdeaProjects/isona/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.spring4all:isona-storage:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-storage/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-storage:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.spring4all:isona-core:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-core/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-core:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.spring4all:isona-web:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/isona-web/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-web:0.0.1-SNAPSHOT: Could not find artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 14, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.spring4all:isona:0.0.1-SNAPSHOT (/Users/lihaifeng/IdeaProjects/isona/pom.xml) has 1 error
[ERROR]     Child module /Users/lihaifeng/IdeaProjects/isona/isona-example-consul of /Users/lihaifeng/IdeaProjects/isona/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

**Comment by dyc87112** [comment]
先编译一下parent模块，再编译其他的
