### ISSUE TITLE
isona在maven编译时依赖无法找到。

### ISSUE THREAD

**Issue by Wuzhibin05** [SpringForAll/isona#8]
C:\Users\Administrator\Desktop\isona>mvn clean package
[INFO] Scanning for projects...
Downloading from nexus-snapshots: http://nexus-snapshots/com/spring4all/isona-pa
rent/0.0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.spring4all:isona-parent:0.0.1-SNAPSHOT
/maven-metadata.xml from/to nexus-snapshots (http://nexus-snapshots): nexus-snap
shots
Downloading from nexus-releases: http://nexus-releases/com/spring4all/isona-pare
nt/0.0.1-SNAPSHOT/isona-parent-0.0.1-SNAPSHOT.pom
Downloading from nexus-snapshots: http://nexus-snapshots/com/spring4all/isona-pa
rent/0.0.1-SNAPSHOT/isona-parent-0.0.1-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-storage:0.0.1-SNAPSH
OT (C:\Users\Administrator\Desktop\isona\isona-storage\pom.xml) points at com.sp
ring4all:isona instead of com.spring4all:isona-parent, please verify your projec
t structure @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-storage:0.0.1-SNAPSHO
T: Could not transfer artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT fr
om/to nexus-releases (http://nexus-releases): nexus-releases and 'parent.relativ
ePath' points at wrong local POM @ line 14, column 10
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-core:0.0.1-SNAPSHOT
(C:\Users\Administrator\Desktop\isona\isona-core\pom.xml) points at com.spring4a
ll:isona instead of com.spring4all:isona-parent, please verify your project stru
cture @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-core:0.0.1-SNAPSHOT:
Failure to transfer com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT from http://n
exus-releases was cached in the local repository, resolution will not be reattem
pted until the update interval of nexus-releases has elapsed or updates are forc
ed. Original error: Could not transfer artifact com.spring4all:isona-parent:pom:
0.0.1-SNAPSHOT from/to nexus-releases (http://nexus-releases): nexus-releases an
d 'parent.relativePath' points at wrong local POM @ line 14, column 10
[WARNING] 'parent.relativePath' of POM com.spring4all:isona-web:0.0.1-SNAPSHOT (
C:\Users\Administrator\Desktop\isona\isona-web\pom.xml) points at com.spring4all
:isona instead of com.spring4all:isona-parent, please verify your project struct
ure @ line 14, column 10
[FATAL] Non-resolvable parent POM for com.spring4all:isona-web:0.0.1-SNAPSHOT: F
ailure to transfer com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT from http://ne
xus-releases was cached in the local repository, resolution will not be reattemp
ted until the update interval of nexus-releases has elapsed or updates are force
d. Original error: Could not transfer artifact com.spring4all:isona-parent:pom:0
.0.1-SNAPSHOT from/to nexus-releases (http://nexus-releases): nexus-releases and
 'parent.relativePath' points at wrong local POM @ line 14, column 10
[ERROR] Child module C:\Users\Administrator\Desktop\isona\isona-example-consul o
f C:\Users\Administrator\Desktop\isona\pom.xml does not exist @
 @
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]
[ERROR]   The project com.spring4all:isona-storage:0.0.1-SNAPSHOT (C:\Users\Admi
nistrator\Desktop\isona\isona-storage\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-storage:0.0.1-SNA
PSHOT: Could not transfer artifact com.spring4all:isona-parent:pom:0.0.1-SNAPSHO
T from/to nexus-releases (http://nexus-releases): nexus-releases and 'parent.rel
ativePath' points at wrong local POM @ line 14, column 10: Unknown host nexus-re
leases -> [Help 2]
[ERROR]
[ERROR]   The project com.spring4all:isona-core:0.0.1-SNAPSHOT (C:\Users\Adminis
trator\Desktop\isona\isona-core\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-core:0.0.1-SNAPSH
OT: Failure to transfer com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT from http
://nexus-releases was cached in the local repository, resolution will not be rea
ttempted until the update interval of nexus-releases has elapsed or updates are
forced. Original error: Could not transfer artifact com.spring4all:isona-parent:
pom:0.0.1-SNAPSHOT from/to nexus-releases (http://nexus-releases): nexus-release
s and 'parent.relativePath' points at wrong local POM @ line 14, column 10 -> [H
elp 2]
[ERROR]
[ERROR]   The project com.spring4all:isona-web:0.0.1-SNAPSHOT (C:\Users\Administ
rator\Desktop\isona\isona-web\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.spring4all:isona-web:0.0.1-SNAPSHO
T: Failure to transfer com.spring4all:isona-parent:pom:0.0.1-SNAPSHOT from http:
//nexus-releases was cached in the local repository, resolution will not be reat
tempted until the update interval of nexus-releases has elapsed or updates are f
orced. Original error: Could not transfer artifact com.spring4all:isona-parent:p
om:0.0.1-SNAPSHOT from/to nexus-releases (http://nexus-releases): nexus-releases
 and 'parent.relativePath' points at wrong local POM @ line 14, column 10 -> [He
lp 2]
[ERROR]
[ERROR]   The project com.spring4all:isona:0.0.1-SNAPSHOT (C:\Users\Administrato
r\Desktop\isona\pom.xml) has 1 error
[ERROR]     Child module C:\Users\Administrator\Desktop\isona\isona-example-cons
ul of C:\Users\Administrator\Desktop\isona\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

**Comment by dyc87112** [comment]
没有上传到nexus，先编译一下parent模块，再编译其他的
